### ISSUE TITLE
Fix npm package name

### ISSUE THREAD

**Issue by ly0va** [matter-labs/onboard#4]
The package name is `@matterlabs/zk-wallet-onboarding`, `mattermost` is the communication app we use that is coincidently a sound-alike :sweat_smile: 

https://github.com/matter-labs-forks/onboard/blob/e32f81e24f6ca0eb71750a649f1ff53964e162b0/README.md#L7

**Comment by keriat** [comment]
@ly0va believe 👽 me or not, it's fixed 😏
